import { z } from "zod";
import { protectedProcedure, router } from "../_core/trpc";
import {
  getPromises,
  getPromiseById,
  createPromise,
  updatePromise,
  deletePromise,
} from "../db";
import { notifyOwner } from "../_core/notification";

export const promisesRouter = router({
  list: protectedProcedure
    .input(
      z.object({
        status: z.enum(["scheduled", "completed", "canceled", "overdue"]).optional(),
        upcoming: z.boolean().optional(),
      }).optional()
    )
    .query(({ ctx, input }) =>
      getPromises(ctx.user.id, {
        status: input?.status,
        upcoming: input?.upcoming,
      })
    ),

  get: protectedProcedure
    .input(z.object({ id: z.number() }))
    .query(({ ctx, input }) => getPromiseById(input.id, ctx.user.id)),

  create: protectedProcedure
    .input(
      z.object({
        salesLogId: z.number().optional(),
        clientId: z.number().optional(),
        clientName: z.string().optional(),
        title: z.string().min(1),
        description: z.string().optional(),
        scheduledAt: z.string(),
      })
    )
    .mutation(({ ctx, input }) =>
      createPromise({
        ...input,
        userId: ctx.user.id,
        scheduledAt: new Date(input.scheduledAt),
        isAutoGenerated: false,
      })
    ),

  update: protectedProcedure
    .input(
      z.object({
        id: z.number(),
        title: z.string().optional(),
        description: z.string().optional(),
        scheduledAt: z.string().optional(),
        status: z.enum(["scheduled", "completed", "canceled", "overdue"]).optional(),
        clientName: z.string().optional(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const { id, scheduledAt, ...rest } = input;
      await updatePromise(id, ctx.user.id, {
        ...rest,
        ...(scheduledAt ? { scheduledAt: new Date(scheduledAt) } : {}),
      });
      return { success: true };
    }),

  complete: protectedProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ ctx, input }) => {
      await updatePromise(input.id, ctx.user.id, { status: "completed" });
      return { success: true };
    }),

  cancel: protectedProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ ctx, input }) => {
      await updatePromise(input.id, ctx.user.id, { status: "canceled" });
      return { success: true };
    }),

  delete: protectedProcedure
    .input(z.object({ id: z.number() }))
    .mutation(({ ctx, input }) => deletePromise(input.id, ctx.user.id)),
});
