CREATE TABLE `attachments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`salesLogId` int,
	`fileName` varchar(300) NOT NULL,
	`fileKey` varchar(500) NOT NULL,
	`fileUrl` text NOT NULL,
	`mimeType` varchar(100),
	`fileSize` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `attachments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `clients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(200) NOT NULL,
	`industry` varchar(100),
	`contactPerson` varchar(100),
	`contactPhone` varchar(50),
	`contactEmail` varchar(320),
	`address` text,
	`notes` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `clients_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deliveries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`orderId` int NOT NULL,
	`clientName` varchar(200) NOT NULL,
	`deliveryStatus` enum('pending','delivered','invoiced','paid') NOT NULL DEFAULT 'pending',
	`deliveredAt` timestamp,
	`revenueAmount` decimal(15,2) NOT NULL,
	`billingStatus` enum('unbilled','billed','paid') NOT NULL DEFAULT 'unbilled',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `deliveries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`clientId` int,
	`salesLogId` int,
	`clientName` varchar(200) NOT NULL,
	`productService` varchar(300) NOT NULL,
	`amount` decimal(15,2) NOT NULL,
	`status` enum('proposal','negotiation','confirmed','canceled') NOT NULL DEFAULT 'proposal',
	`contractDate` timestamp,
	`expectedDeliveryDate` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `promises` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`salesLogId` int,
	`clientId` int,
	`clientName` varchar(200),
	`title` varchar(300) NOT NULL,
	`description` text,
	`scheduledAt` timestamp NOT NULL,
	`status` enum('scheduled','completed','canceled','overdue') NOT NULL DEFAULT 'scheduled',
	`reminderSent` boolean NOT NULL DEFAULT false,
	`isAutoGenerated` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `promises_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `salesLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`clientId` int,
	`clientName` varchar(200),
	`contactPerson` varchar(100),
	`location` varchar(200),
	`visitedAt` timestamp NOT NULL,
	`rawContent` text NOT NULL,
	`aiSummary` text,
	`aiExtracted` json,
	`audioUrl` text,
	`transcribedText` text,
	`isProcessed` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `salesLogs_id` PRIMARY KEY(`id`)
);
