import {
  int,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
  decimal,
  boolean,
  json,
} from "drizzle-orm/mysql-core";

// ─── Users ────────────────────────────────────────────────────────────────────
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// ─── Clients (고객사) ──────────────────────────────────────────────────────────
export const clients = mysqlTable("clients", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  name: varchar("name", { length: 200 }).notNull(),
  industry: varchar("industry", { length: 100 }),
  contactPerson: varchar("contactPerson", { length: 100 }),
  contactPhone: varchar("contactPhone", { length: 50 }),
  contactEmail: varchar("contactEmail", { length: 320 }),
  address: text("address"),
  notes: text("notes"),
  isActive: boolean("isActive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Client = typeof clients.$inferSelect;
export type InsertClient = typeof clients.$inferInsert;

// ─── SalesLogs (영업일지) ──────────────────────────────────────────────────────
export const salesLogs = mysqlTable("salesLogs", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  clientId: int("clientId"),
  clientName: varchar("clientName", { length: 200 }),
  contactPerson: varchar("contactPerson", { length: 100 }),
  location: varchar("location", { length: 200 }),
  visitedAt: timestamp("visitedAt").notNull(),
  rawContent: text("rawContent").notNull(),
  aiSummary: text("aiSummary"),
  aiExtracted: json("aiExtracted"), // { nextActions, amount, keywords, sentiment }
  audioUrl: text("audioUrl"),
  transcribedText: text("transcribedText"),
  isProcessed: boolean("isProcessed").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SalesLog = typeof salesLogs.$inferSelect;
export type InsertSalesLog = typeof salesLogs.$inferInsert;

// ─── Promises (일정 관리) ──────────────────────────────────────────────────────
export const promises = mysqlTable("promises", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  salesLogId: int("salesLogId"),
  clientId: int("clientId"),
  clientName: varchar("clientName", { length: 200 }),
  title: varchar("title", { length: 300 }).notNull(),
  description: text("description"),
  scheduledAt: timestamp("scheduledAt").notNull(),
  status: mysqlEnum("status", ["scheduled", "completed", "canceled", "overdue"])
    .default("scheduled")
    .notNull(),
  reminderSent: boolean("reminderSent").default(false).notNull(),
  isAutoGenerated: boolean("isAutoGenerated").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Promise = typeof promises.$inferSelect;
export type InsertPromise = typeof promises.$inferInsert;

// ─── Orders (수주) ─────────────────────────────────────────────────────────────
export const orders = mysqlTable("orders", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  clientId: int("clientId"),
  salesLogId: int("salesLogId"),
  clientName: varchar("clientName", { length: 200 }).notNull(),
  productService: varchar("productService", { length: 300 }).notNull(),
  amount: decimal("amount", { precision: 15, scale: 2 }).notNull(),
  status: mysqlEnum("status", ["proposal", "negotiation", "confirmed", "canceled"])
    .default("proposal")
    .notNull(),
  contractDate: timestamp("contractDate"),
  expectedDeliveryDate: timestamp("expectedDeliveryDate"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Order = typeof orders.$inferSelect;
export type InsertOrder = typeof orders.$inferInsert;

// ─── Deliveries (납품/매출) ────────────────────────────────────────────────────
export const deliveries = mysqlTable("deliveries", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  orderId: int("orderId").notNull(),
  clientName: varchar("clientName", { length: 200 }).notNull(),
  deliveryStatus: mysqlEnum("deliveryStatus", ["pending", "delivered", "invoiced", "paid"])
    .default("pending")
    .notNull(),
  deliveredAt: timestamp("deliveredAt"),
  revenueAmount: decimal("revenueAmount", { precision: 15, scale: 2 }).notNull(),
  billingStatus: mysqlEnum("billingStatus", ["unbilled", "billed", "paid"])
    .default("unbilled")
    .notNull(),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Delivery = typeof deliveries.$inferSelect;
export type InsertDelivery = typeof deliveries.$inferInsert;

// ─── Attachments (첨부파일) ────────────────────────────────────────────────────
export const attachments = mysqlTable("attachments", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  salesLogId: int("salesLogId"),
  fileName: varchar("fileName", { length: 300 }).notNull(),
  fileKey: varchar("fileKey", { length: 500 }).notNull(),
  fileUrl: text("fileUrl").notNull(),
  mimeType: varchar("mimeType", { length: 100 }),
  fileSize: int("fileSize"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Attachment = typeof attachments.$inferSelect;
export type InsertAttachment = typeof attachments.$inferInsert;
